name = "javascript-design-patterns"
compatibility_date = "2024-05-27"
pages_build_output_dir = ".vercel/output/static"

# Build configuration for Pages
[build]
command = "npx @cloudflare/next-on-pages@1"

[build.upload]
format = "service-worker"

# Environment variables
[vars]
NODE_ENV = "production"

# Compatibility flags for Next.js
compatibility_flags = ["nodejs_compat"]

# KV namespace bindings (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Durable Objects bindings (if needed)
# [[durable_objects.bindings]]
# name = "DO"
# class_name = "DurableObject"
# script_name = "javascript-design-patterns"

# Routes
[env.production.routes]
pattern = "javascript-design-patterns.workers.dev/*"
zone_name = ""

[env.staging.routes]
pattern = "staging-javascript-design-patterns.workers.dev/*"
zone_name = "" 