name = "javascript-design-patterns"
main = ".worker-next/index.js"
compatibility_date = "2024-05-27"

# Worker configuration
[site]
bucket = ".worker-next/assets"

# Build configuration
[build]
command = "npm run build:worker"

# Environment variables
[vars]
NODE_ENV = "production"

# Compatibility flags for Next.js
compatibility_flags = ["nodejs_compat"]

# KV namespace bindings (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Durable Objects bindings (if needed)
# [[durable_objects.bindings]]
# name = "DO"
# class_name = "DurableObject"
# script_name = "javascript-design-patterns"

# Routes
[env.production.routes]
pattern = "javascript-design-patterns.workers.dev/*"
zone_name = ""

[env.staging.routes]
pattern = "staging-javascript-design-patterns.workers.dev/*"
zone_name = "" 